services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.example
    environment:
      DB_DSN: "host=postgres user=testWallet password=Wallet11# dbname=wallet_service port=5432 sslmode=disable TimeZone=UTC"
      REDIS_ADDR: redis:6379
      HTTP_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: wallet_service
      POSTGRES_USER: testWallet
      POSTGRES_PASSWORD: "Wallet11#"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testWallet -d wallet_service"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  postgres_data:
